### ISSUE TITLE
AlethZero crashes when parsing solidity contract

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#1300]
example code:

```
contract main
{
       function method () returns (bool)
       {
		if (ripemd160.gas(200000) ('teststring', 200000) != 0xcd566972b5e50104011a92b59fa8e0b1234851ae)		
			return false;
       }
}
```

**Comment by LefterisJP** [comment]
Here is the backtrace for convenience

```
(gdb) r
Starting program: /home/lefteris/ew/cpp-ethereum/build/solc/solc /home/lefteris/test.sol
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Assertion failed:1 <= _number && _number <= 16 [func=dev::eth::Instruction dev::eth::swapInstruction(unsigned int), line=213, file=/home/lefteris/ew/cpp-ethereum/libsolidity/../libevmcore/Instruction.h]

Program received signal SIGTRAP, Trace/breakpoint trap.
dev::assertAux (_a=false, _aStr=0x7ffff767ca3f "1 <= _number && _number <= 16", _line=213, _file=0x7ffff767c9f8 "/home/lefteris/ew/cpp-ethereum/libsolidity/../libevmcore/Instruction.h", _func=0x7ffff767dac0 <dev::eth::swapInstruction(unsigned int)::__PRETTY_FUNCTION__> "dev::eth::Instruction dev::eth::swapInstruction(unsigned int)")
    at /home/lefteris/ew/cpp-ethereum/libsolidity/../libdevcore/Common.h:160
160             return !ret;
(gdb) bt
#0  dev::assertAux (_a=false, _aStr=0x7ffff767ca3f "1 <= _number && _number <= 16", _line=213, _file=0x7ffff767c9f8 "/home/lefteris/ew/cpp-ethereum/libsolidity/../libevmcore/Instruction.h", _func=0x7ffff767dac0 <dev::eth::swapInstruction(unsigned int)::__PRETTY_FUNCTION__> "dev::eth::Instruction dev::eth::swapInstruction(unsigned int)")
    at /home/lefteris/ew/cpp-ethereum/libsolidity/../libdevcore/Common.h:160
#1  0x00007ffff75db7cd in dev::eth::swapInstruction (_number=0) at /home/lefteris/ew/cpp-ethereum/libsolidity/../libevmcore/Instruction.h:213
#2  0x00007ffff75f2b1e in dev::solidity::CompilerUtils::moveToStackVariable (this=0x7fffffffd0f0, _variable=...) at /home/lefteris/ew/cpp-ethereum/libsolidity/CompilerUtils.cpp:146
#3  0x00007ffff7644dd1 in dev::solidity::Compiler::visit (this=0xf8cdd0, _return=...) at /home/lefteris/ew/cpp-ethereum/libsolidity/Compiler.cpp:493
#4  0x00007ffff76590e6 in dev::solidity::Return::accept (this=0xf89900, _visitor=...) at /home/lefteris/ew/cpp-ethereum/libsolidity/../libsolidity/AST_accept.h:486
#5  0x00007ffff76444d8 in dev::solidity::Compiler::visit (this=0xf8cdd0, _ifStatement=...) at /home/lefteris/ew/cpp-ethereum/libsolidity/Compiler.cpp:397
#6  0x00007ffff7658a8e in dev::solidity::IfStatement::accept (this=0xf89be0, _visitor=...) at /home/lefteris/ew/cpp-ethereum/libsolidity/../libsolidity/AST_accept.h:392
#7  0x00007ffff76629fa in dev::solidity::ASTNode::listAccept<dev::solidity::Statement> (_list=std::vector of length 1, capacity 1 = {...}, _visitor=...) at /home/lefteris/ew/cpp-ethereum/libsolidity/../libsolidity/AST.h:70
#8  0x00007ffff76588b7 in dev::solidity::Block::accept (this=0xf89c70, _visitor=...) at /home/lefteris/ew/cpp-ethereum/libsolidity/../libsolidity/AST_accept.h:362
#9  0x00007ffff7645285 in dev::solidity::Compiler::appendModifierOrFunctionCode (this=0xf8cdd0) at /home/lefteris/ew/cpp-ethereum/libsolidity/Compiler.cpp:541
#10 0x00007ffff7643db1 in dev::solidity::Compiler::visit (this=0xf8cdd0, _function=...) at /home/lefteris/ew/cpp-ethereum/libsolidity/Compiler.cpp:341
#11 0x00007ffff7657db6 in dev::solidity::FunctionDefinition::accept (this=0xf89ce0, _visitor=...) at /home/lefteris/ew/cpp-ethereum/libsolidity/../libsolidity/AST_accept.h:185
Python Exception <type 'exceptions.ValueError'> Cannot find type const std::map<dev::solidity::ContractDefinition const*, std::vector<unsigned char, std::allocator<unsigned char> > const*, std::less<dev::solidity::ContractDefinition const*>, std::allocator<std::pair<dev::solidity::ContractDefinition const* const, std::vector<unsigned char, std::allocator<unsigned char> > const*> > >::_Rep_type: 
#12 0x00007ffff7641666 in dev::solidity::Compiler::compileContract (this=0xf8cdd0, _contract=..., _contracts=std::map with 0 elements) at /home/lefteris/ew/cpp-ethereum/libsolidity/Compiler.cpp:63
#13 0x00007ffff75639c0 in dev::solidity::CompilerStack::compile (this=0xf8a370, _optimize=false) at /home/lefteris/ew/cpp-ethereum/libsolidity/CompilerStack.cpp:142
#14 0x000000000044a0ee in dev::solidity::CommandLineInterface::processInput (this=0x7fffffffdd10) at /home/lefteris/ew/cpp-ethereum/solc/CommandLineInterface.cpp:303

```
