### ISSUE TITLE
AZ hang "Searching for seedHash" ethash_calculate_dag_item

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1661]
develop 026494f

Ran AZ and it was stuck on:
```
State root: 9178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4e
Block Hash: fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca
Block RLP: [ [ "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x1DCC4DE8DEC75D7AAB85B567B6CCD41AD312451B948A7413F0A142FD40D49347, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x9178D0F23C965D81F0834A4C72C6253CE6830F4022B1359AAEBFC1ECBA442D4E, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x20000, 0x0, 0x2FEFD8, 0x0, 0x0, 0x0, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", "\x00\x00\x00\x00\x00\x00\x00*" ], [ ], [ ] ]
Block Hex: f901f8f901f3a00000000000000000000000000000000000000000000000000000000000000000a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347940000000000000000000000000000000000000000a09178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4ea056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008302000080832fefd8808080a0000000000000000000000000000000000000000000000000000000000000000088000000000000002ac0c0
eth Network protocol version: 60
Client database version: 11785
*N* [ 05:22:24 PM | main ] Id: 44348e6f50b7d533158856c3bbc1d4ca2aa89726a97cd7bc3762ca3f26b826fc7a3b33b2f21bad468ad755a965d47e2406a06303ca8a7cb1fededd09334b63ba
*** [ 05:22:24 PM | main ] Opened blockchain DB. Latest: 8ebe8cd402397c60ae60d5b8868dbfd96286d22a9adaecf5c2c1df17876afb66
*** [ 05:22:24 PM | main ] Opened state DB.
*** [ 05:22:24 PM | main ] Spawning eth
--- [ 05:22:24 PM | eth ] startedWorking()
--- [ 05:22:24 PM | eth ] 92216 8ebe8cd402397c60ae60d5b8868dbfd96286d22a9adaecf5c2c1df17876afb66
--- [ 05:22:24 PM | eth ] Searching for seedHash of epoch 0
--- [ 05:22:24 PM | eth ] Epoch 0 is 00000000…
--- [ 05:22:24 PM | eth ] Pre: 33a185d9cae8be50c3ae844fb7357a29c8d4942b9c7ac6cdc352e622f135a0fa fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca 0000000000000000000000000000000000000000000000000000000000000000 0000000000000000000000000000000000000000 9178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4e 0000000000000000000000000000000000000000000000000000000000000000 0000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 131072 1 3141592 0 1429230144 0000000000000000000000000000000000000000000000000000000000000000 0000000000000000 (0000000000000000000000000000000000000000000000000000000000000000)
--- [ 05:22:24 PM | eth ] Post: 927464f181accb9e3450ca8d07302a477df67db0e3588b3caf580c5db1ee8ebe 78dec18c6d7da925bbe773c315653cdc70f6444ed6c1de9ac30bdb36cff74c3b 0000000000000000000000000000000000000000000000000000000000000000 0000000000000000000000000000000000000000 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421 0000000000000000000000000000000000000000000000000000000000000000 0000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 131072 1 3141592 0 1429230144 0000000000000000000000000000000000000000000000000000000000000000 0000000000000000 (0000000000000000000000000000000000000000000000000000000000000000)
--- [ 05:22:24 PM | eth ] Pre: 872a9a8717aa85f598d0f713d1357dcdd8daf5b6d2af9dc94759d2360af6b91b ; Post: defb1d4df5a71e5ae01e20c176c1038273417183bca670ee2af438058b3df328
--- [ 05:22:24 PM | eth ] Searching for seedHash of epoch 3
--- [ 05:22:24 PM | eth ] Epoch 0 is 00000000…
--- [ 05:22:24 PM | eth ] Epoch 1 is 290decd9…
--- [ 05:22:24 PM | eth ] Epoch 2 is 510e4e77…
--- [ 05:22:24 PM | eth ] Epoch 3 is 356e5a2c…
--- [ 05:22:24 PM | eth ] Pre: 9615a06e4b0162097f526e429b090072c35babf03c137a2f4b647f0b0674cb5a 8ebe8cd402397c60ae60d5b8868dbfd96286d22a9adaecf5c2c1df17876afb66 0000000000000000000000000000000000000000000000000000000000000000 0000000000000000000000000000000000000000 65d3fe2ad7189bd7da5226d4eea42a91dc3c34499cdb64c2ff8089a79f300638 0000000000000000000000000000000000000000000000000000000000000000 0000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 7261172 92217 3141592 0 1429230144 0000000000000000000000000000000000000000000000000000000000000000 0000000000000000 (356e5a2cc1eba076e650ac7473fccc37952b46bc2e419a200cec0c451dce2336)
--- [ 05:22:24 PM | eth ] Post: 9615a06e4b0162097f526e429b090072c35babf03c137a2f4b647f0b0674cb5a 8ebe8cd402397c60ae60d5b8868dbfd96286d22a9adaecf5c2c1df17876afb66 0000000000000000000000000000000000000000000000000000000000000000 0000000000000000000000000000000000000000 65d3fe2ad7189bd7da5226d4eea42a91dc3c34499cdb64c2ff8089a79f300638 0000000000000000000000000000000000000000000000000000000000000000 0000000000000000000000000000000000000000000000000000000000000000 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 7261172 92217 3141592 0 1429230144 0000000000000000000000000000000000000000000000000000000000000000 0000000000000000 (356e5a2cc1eba076e650ac7473fccc37952b46bc2e419a200cec0c451dce2336)
--- [ 05:22:24 PM | eth ] Pre: 5736dbc58a2d5ebd028490dd33516b3a84e92d2eb18a4f9f6abc3e4678abe266 ; Post: 5736dbc58a2d5ebd028490dd33516b3a84e92d2eb18a4f9f6abc3e4678abe266
qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method
(o) [ 05:22:25 PM | main ] +++ 0 00000000…
(o) [ 05:22:25 PM | main ] Blockchain changed!
(o) [ 05:22:25 PM | main ] refreshBlockChain()
--- [ 05:22:55 PM | main ] Searching for seedHash 356e5a2c…
```

bt:
```
#0  0x00007fe73c5e4ed4 in ethash_calculate_dag_item ()
   from /home/user/cpp-ethereum/mar22build/libethcore/libethcore.so
#1  0x00007fe73c5e5141 in ethash_compute_full_data ()
   from /home/user/cpp-ethereum/mar22build/libethcore/libethcore.so
#2  0x00007fe73c5d8359 in ethash_prep_full (full=0x7fe64d1d4010, 
    params=0x7fff962d1450, cache=0x7fe64c174010)
    at /home/user/cpp-ethereum/libethcore/../libethash/ethash.h:106
#3  0x00007fe73c5d9933 in dev::eth::EthashAux::full (_seedHash=..., _dest=...)
    at /home/user/cpp-ethereum/libethcore/EthashAux.cpp:189
#4  0x00007fe73c5da035 in dev::eth::EthashAux::eval (_seedHash=..., 
    _headerHash=..., _nonce=...)
    at /home/user/cpp-ethereum/libethcore/EthashAux.cpp:225
#5  0x00007fe73c5d9da9 in dev::eth::EthashAux::eval (_header=..., _nonce=...)
    at /home/user/cpp-ethereum/libethcore/EthashAux.cpp:203
#6  0x000000000068448e in dev::eth::EthashAux::eval (_header=...)
    at /home/user/cpp-ethereum/alethzero/../libethcore/EthashAux.h:66
#7  0x0000000000675e43 in Main::on_blocks_currentItemChanged (
    this=0x7fff962d3950)
    at /home/user/cpp-ethereum/alethzero/MainWin.cpp:1488
#8  0x00000000006e6117 in Main::qt_static_metacall (_o=0x7fff962d3950, 
    _c=QMetaObject::InvokeMetaMethod, _id=35, _a=0x7fff962d27b0)
    at /home/user/cpp-ethereum/mar22build/alethzero/moc_MainWin.cpp:334
#9  0x00000000006e6554 in Main::qt_metacall (this=0x7fff962d3950, 
    _c=QMetaObject::InvokeMetaMethod, _id=35, _a=0x7fff962d27b0)
    at /home/user/cpp-ethereum/mar22build/alethzero/moc_MainWin.cpp:400
#10 0x00007fe73db50493 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /opt/Qt54/5.4/gcc_64/lib/libQt5Core.so.5
#11 0x00007fe73d3e2c6f in QListWidget::currentItemChanged(QListWidgetItem*, QListWidgetItem*) () from /opt/Qt54/5.4/gcc_64/lib/libQt5Widgets.so.5
#12 0x00007fe73d3e4280 in ?? () from /opt/Qt54/5.4/gcc_64/lib/libQt5Widgets.so.5
#13 0x00007fe73db5001a in QMetaObject::activate(QObject*, int, int, void**) ()
   from /opt/Qt54/5.4/gcc_64/lib/libQt5Core.so.5
#14 0x00007fe73dad458a in QItemSelectionModel::currentChanged(QModelIndex const&, QModelIndex const&) () from /opt/Qt54/5.4/gcc_64/lib/libQt5Core.so.5
#15 0x00007fe73dad466d in QItemSelectionModel::setCurrentIndex(QModelIndex const&, QFlags<QItemSelectionModel::SelectionFlag>) ()
   from /opt/Qt54/5.4/gcc_64/lib/libQt5Core.so.5
#16 0x00007fe73d3e476e in QListWidget::setCurrentRow(int) ()
   from /opt/Qt54/5.4/gcc_64/lib/libQt5Widgets.so.5
#17 0x0000000000671f1c in Main::refreshBlockChain (this=0x7fff962d3950)
    at /home/user/cpp-ethereum/alethzero/MainWin.cpp:1198
#18 0x0000000000663d40 in Main::onNewBlock (this=0x7fff962d3950)
    at /home/user/cpp-ethereum/alethzero/MainWin.cpp:391
#19 0x0000000000662959 in Main::__lambda171::operator() (__closure=0x1c67ed0)
    at /home/user/cpp-ethereum/alethzero/MainWin.cpp:309
#20 0x000000000067f29d in std::_Function_handler<void(const std::vector<dev::eth::LocalisedLogEntry, std::allocator<dev::eth::LocalisedLogEntry> >&), Main::installWatches()::__lambda171>::_M_invoke(const std::_Any_data &, const std::vector<dev::eth::LocalisedLogEntry, std::allocator<dev::eth::LocalisedLogEntry> > &) (
    __functor=..., __args#0=...) at /usr/include/c++/4.8/functional:2071
#21 0x000000000069ca91 in std::function<void (std::vector<dev::eth::LocalisedLogEntry, std::allocator<dev::eth::LocalisedLogEntry> > const&)>::operator()(std::vector<dev::eth::LocalisedLogEntry, std::allocator<dev::eth::LocalisedLogEntry> > const&) const (this=0x7fff962d34c0, __args#0=...)
    at /usr/include/c++/4.8/functional:2464
#22 0x0000000000662838 in Main::installWatch(dev::FixedHash<32u>, std::function<void (std::vector<dev::eth::LocalisedLogEntry, std::allocator<dev::eth::LocalisedLogEntry> > const&)> const&) (this=0x7fff962d3950, _tf=..., _f=...)
    at /home/user/cpp-ethereum/alethzero/MainWin.cpp:295
#23 0x0000000000662a3f in Main::installWatches (this=0x7fff962d3950)
    at /home/user/cpp-ethereum/alethzero/MainWin.cpp:310
#24 0x00000000006613bb in Main::Main (this=0x7fff962d3950, parent=0x0)
    at /home/user/cpp-ethereum/alethzero/MainWin.cpp:200
#25 0x000000000064a9ad in main (argc=1, argv=0x7fff962d3d28)
    at /home/user/cpp-ethereum/alethzero/main.cpp:8
```

**Comment by ethers** [comment]
AZ just started
