### ISSUE TITLE
clEnqueueWriteBuffer segfault

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/cpp-ethereum#2070]
When attempting to GPU mine in Linux I am getting a segfault inside the C++ OpenCL wrapper's `clEnqueueWriteBuffer()`. That function is supposed to be able to throw when there is an error but it does not. Here is the backtrace:

```
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff64b4967 in cl::CommandQueue::enqueueWriteBuffer (this=0x7fffc00008f8, buffer=..., blocking=0, offset=0, size=32, ptr=0x7fffd0c2c610, events=0x0, event=0x0) at /usr/include/CL/cl.hpp:2640
#2  0x00007ffff64b0129 in ethash_cl_miner::search (this=0x7fffc00008f0, header=0x7fffd0c2c610 "\024\211D\275ǜ\377\235Y\242\217\034$.\236Խr}\262_\215\271ǔ\326J\275\263\r1\245\034CCJ\340\231\337imh.h\320a\034ɹ\355\246\066Fa4\326\350W\310lK\326\355(", target=859041926, hook=...)
    at /home/lefteris/ew/cpp-ethereum/libethash-cl/ethash_cl_miner.cpp:312
#3  0x00007ffff6625fb2 in dev::eth::Ethash::GPUMiner::workLoop (this=0xf14fd0) at /home/lefteris/ew/cpp-ethereum/libethcore/Ethash.cpp:352
#4  0x00007ffff4207a61 in dev::Worker::<lambda()>::operator()(void) const (__closure=0xf13ac8) at /home/lefteris/ew/cpp-ethereum/libdevcore/Worker.cpp:55
#5  0x00007ffff42091bc in std::_Bind_simple<dev::Worker::startWorking()::<lambda()>()>::_M_invoke<>(std::_Index_tuple<>) (this=0xf13ac8) at /usr/include/c++/5.1.0/functional:1531
#6  0x00007ffff4209125 in std::_Bind_simple<dev::Worker::startWorking()::<lambda()>()>::operator()(void) (this=0xf13ac8) at /usr/include/c++/5.1.0/functional:1520
#7  0x00007ffff42090c4 in std::thread::_Impl<std::_Bind_simple<dev::Worker::startWorking()::<lambda()>()> >::_M_run(void) (this=0xf13ab0) at /usr/include/c++/5.1.0/thread:115
#8  0x00007ffff33c52f0 in std::(anonymous namespace)::execute_native_thread_routine (__p=<optimized out>) at /build/gcc-multilib/src/gcc-5-20150519/libstdc++-v3/src/c++11/thread.cc:84
#9  0x00007ffff3695354 in start_thread () from /usr/lib/libpthread.so.0
#10 0x00007ffff2b37bfd in clone () from /usr/lib/libc.so.6
```

- **GPU**: GeForce GTX 770
- **System**: Linux 4.0.4-2-ARCH
- **OpenCL**: Nvidia OpenCL 1.1

**Comment by gavofyork** [comment]
upstream bug?

**Comment by LefterisJP** [comment]
Let's keep it open for a while until the network goes back in shape. Will attempt to GPU mine again with the new OpenCL changes and see if this happens again.

**Comment by gavofyork** [comment]
closing until this can be properly diagnosed.
