### ISSUE TITLE
TrieDB assertion failure during blockchain verification

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/cpp-ethereum#2205]
In a totally new machine wtih Ubuntu 14.04 I was downloading the blockchain. No matter what I do it's stuck at block 490591. While attempting to debug it by building a Debug version there is always the same assertion hit inside TrieDB while trying to verify a block.

This is how the logs with verbosity 9 look like right before the assertion hits:
```
⧎ ◌  12:34:52|p2p  Hello: Geth/v0.9.31/linux/go1.4.2 V[ 4 ] ##34584f37… (eth,60) 0
⧎ ℹ  12:34:52|p2p  p2p.host.peer.register ##34584f37…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #c8369054…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #c1b5807f…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #f35dab26…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #a9eca4a8…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #41f33592…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #80d2dfed…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #fd27567b…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #f8a3c793…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #3026a48d…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #53e68e83…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #6bf46a51…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #1fb99961…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #1e8ae047…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #6086e508…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #a4967993…
▧ ◌  12:34:52|verifier1  Expected trie root: 7a7abf27b12d5a57b1439e29786f641ca99893612e29cc4597bf669e9dc56e91
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
☍ ◌  12:34:52|eth  Attempting import of #265463eb… ...
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #5545d886…
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: 59608e2787768e28b01f9611bdd2132907e1adbdea2383780533d7dd24e48b4e
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #2a4b6fab…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #bfc95d4f…
Press Enter[New Thread 0x2aaadaa19700 (LWP 6213)]
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: 62fa1c9b072c3edb5c28548c17210972f6151721a297ec2172a67920cabbae5f
▧ ◌  12:34:52|verifier1  Expected uncle hash: 26030206fa91ef5500edcd693d60807b950f251490bb26daec11357ae236c724
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #b9d99360…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #2a2972d0…
▧ ◌  12:34:52|verifier1  Expected trie root: 7ec78e0284f59ed0fefeb3b0d1dc0654621f1c6154e09dabb482b99a873f8776
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #2444f76b…
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: f6b8e9a8fccd6b2588248917f81b7cca9cc05a393281dfb7a33e5370c099d882
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: 196e3b0b082bdc52fd71f8589cc316ec299451cc0bd731abb3427565bd8fcc7f
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #06acdeb6…
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: f3c1ea4fedefbcfbc060a7af4e4d1594cceb72d31c4c9c1ebb58b0b34449c508
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #c3b9e8ed…
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: 9dbe706c57095e7e1e8d30a4b520a1aae53e6c9042cc031d5c3d996617a2ebfd
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #86e199fb…
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #c4750b00…
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: d7e9c50e3fe5b82d5f77836b3df9dd49f306205d532467c15cd5e2fdf02b19d0
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #d18c9d97…
▧ ◌  12:34:52|verifier1  Expected trie root: 96847550502f055c15c8da76bf71f40c64f08d17d99c90f826d5591a572b75aa
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
┉┅▶  12:34:52|p2p|47046ae0…|Geth/v0.9.30/darwin/go1.4.2  Queued vaguely legit-looking transaction #2c371f80…
▧ ◌  12:34:52|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  12:34:52|verifier1  Expected trie root: d190618b83b937b54c8a19bb701adb8b19b6e661bfcb98f2e03c1232b0d06a5e
▧ ◌  12:34:52|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
Press Entereth: /home/minekraft/lefteris/cpp-ethereum/libethereum/../libdevcore/TrieDB.h:953: dev::bytes dev::GenericTrieDB<_DB>::deleteAt(const dev::RLP&, dev::NibbleSlice) [with _DB = dev::OverlayDB; dev::bytes = std::vector<unsigned char>]: Assertion `_orig.isList() 
&& (_orig.itemCount() == 2 || _orig.itemCount() == 17)' failed.
```

And this is the backtrace of the time the assertion hits:
```
Program received signal SIGABRT, Aborted.
[Switching to Thread 0x2aaab88bf700 (LWP 6208)]
0x00002aaaad740cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00002aaaad740cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00002aaaad7440d8 in __GI_abort () at abort.c:89
#2  0x00002aaaad739b86 in __assert_fail_base (fmt=0x2aaaad88a830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x2aaaab91b878 "_orig.isList() && (_orig.itemCount() == 2 || _orig.itemCount() == 17)", 
    file=file@entry=0x2aaaab91b3d0 "/home/minekraft/lefteris/cpp-ethereum/libethereum/../libdevcore/TrieDB.h", line=line@entry=953, 
    function=function@entry=0x2aaaab91be00 <dev::GenericTrieDB<dev::OverlayDB>::deleteAt(dev::RLP const&, dev::NibbleSlice)::__PRETTY_FUNCTION__> "dev::bytes dev::GenericTrieDB<_DB>::deleteAt(const dev::RLP&, dev::NibbleSlice) [with _DB = dev::OverlayDB; dev::bytes = std::vector<unsigned char>]") at assert.c:92
#3  0x00002aaaad739c32 in __GI___assert_fail (assertion=0x2aaaab91b878 "_orig.isList() && (_orig.itemCount() == 2 || _orig.itemCount() == 17)", file=0x2aaaab91b3d0 "/home/minekraft/lefteris/cpp-ethereum/libethereum/../libdevcore/TrieDB.h", line=953, 
    function=0x2aaaab91be00 <dev::GenericTrieDB<dev::OverlayDB>::deleteAt(dev::RLP const&, dev::NibbleSlice)::__PRETTY_FUNCTION__> "dev::bytes dev::GenericTrieDB<_DB>::deleteAt(const dev::RLP&, dev::NibbleSlice) [with _DB = dev::OverlayDB; dev::bytes = std::vector<unsigned char>]") at assert.c:101
#4  0x00002aaaab86897b in dev::GenericTrieDB<dev::OverlayDB>::deleteAt (this=0x2aaab88b7cb0, _orig=..., _k=...) at /home/minekraft/lefteris/cpp-ethereum/libethereum/../libdevcore/TrieDB.h:953
#5  0x00002aaaab86bb05 in dev::GenericTrieDB<dev::OverlayDB>::deleteAtAux (this=0x2aaab88b7cb0, _out=..., _orig=..., _k=...) at /home/minekraft/lefteris/cpp-ethereum/libethereum/../libdevcore/TrieDB.h:1052
#6  0x00002aaaab868f55 in dev::GenericTrieDB<dev::OverlayDB>::deleteAt (this=0x2aaab88b7cb0, _orig=..., _k=...) at /home/minekraft/lefteris/cpp-ethereum/libethereum/../libdevcore/TrieDB.h:1018
#7  0x00002aaaab86bb05 in dev::GenericTrieDB<dev::OverlayDB>::deleteAtAux (this=0x2aaab88b7cb0, _out=..., _orig=..., _k=...) at /home/minekraft/lefteris/cpp-ethereum/libethereum/../libdevcore/TrieDB.h:1052
#8  0x00002aaaab868f55 in dev::GenericTrieDB<dev::OverlayDB>::deleteAt (this=0x2aaab88b7cb0, _orig=..., _k=...) at /home/minekraft/lefteris/cpp-ethereum/libethereum/../libdevcore/TrieDB.h:1018
#9  0x00002aaaab864e82 in dev::GenericTrieDB<dev::OverlayDB>::remove (this=0x2aaab88b7cb0, _key=...) at /home/minekraft/lefteris/cpp-ethereum/libethereum/../libdevcore/TrieDB.h:919
#10 0x00002aaaab85ee76 in dev::SpecificTrieDB<dev::GenericTrieDB<dev::OverlayDB>, dev::FixedHash<32u> >::remove (this=0x2aaab88b7cb0, _k=...) at /home/minekraft/lefteris/cpp-ethereum/libethereum/../libdevcore/TrieDB.h:329
#11 0x00002aaaab8573b6 in dev::HashedGenericTrieDB<dev::OverlayDB>::remove (this=0x2aaab88b7cb0, _key=...) at /home/minekraft/lefteris/cpp-ethereum/libethereum/../libdevcore/TrieDB.h:388
#12 0x00002aaaab84c66c in dev::SpecificTrieDB<dev::HashedGenericTrieDB<dev::OverlayDB>, dev::FixedHash<32u> >::remove (this=0x2aaab88b7cb0, _k=...) at /home/minekraft/lefteris/cpp-ethereum/libethereum/../libdevcore/TrieDB.h:329
#13 0x00002aaaab8448b4 in dev::eth::commit<dev::OverlayDB> (_cache=..., _db=..., _state=...) at /home/minekraft/lefteris/cpp-ethereum/libethereum/State.h:448
#14 0x00002aaaab835fb9 in dev::eth::State::commit (this=0x2aaab88bdba0) at /home/minekraft/lefteris/cpp-ethereum/libethereum/State.cpp:291
#15 0x00002aaaab83d14e in dev::eth::State::execute(std::vector<dev::FixedHash<32u>, std::allocator<dev::FixedHash<32u> > > const&, dev::eth::Transaction const&, dev::eth::Permanence, std::function<void (unsigned long, dev::eth::Instruction, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, dev::eth::VM*, dev::eth::ExtVMFace const*)> const&) (this=0x2aaab88bdba0, _lh=..., _t=..., _p=dev::eth::Committed, _onOp=...) at /home/minekraft/lefteris/cpp-ethereum/libethereum/State.cpp:1239
#16 0x00002aaaab837ecc in dev::eth::State::enact (this=0x2aaab88bdba0, _block=..., _bc=..., _ir=2) at /home/minekraft/lefteris/cpp-ethereum/libethereum/State.cpp:652
#17 0x00002aaaab8365eb in dev::eth::State::enactOn (this=0x2aaab88bdba0, _block=..., _bc=..., _ir=2) at /home/minekraft/lefteris/cpp-ethereum/libethereum/State.cpp:438
#18 0x00002aaaab807fca in dev::eth::BlockChain::import (this=0x5cb9f0, _block=..., _db=..., _ir=2) at /home/minekraft/lefteris/cpp-ethereum/libethereum/BlockChain.cpp:480
#19 0x00002aaaab806d50 in dev::eth::BlockChain::sync (this=0x5cb9f0, _bq=..., _stateDB=..., _max=50) at /home/minekraft/lefteris/cpp-ethereum/libethereum/BlockChain.cpp:328
#20 0x00002aaaab8a70b8 in dev::eth::Client::syncBlockQueue (this=0x5cb640) at /home/minekraft/lefteris/cpp-ethereum/libethereum/Client.cpp:623
#21 0x00002aaaab8a90ea in dev::eth::Client::doWork (this=0x5cb640) at /home/minekraft/lefteris/cpp-ethereum/libethereum/Client.cpp:827
#22 0x00002aaaac6084c3 in dev::Worker::workLoop (this=0x5cb990) at /home/minekraft/lefteris/cpp-ethereum/libdevcore/Worker.cpp:115
#23 0x00002aaaac607ee8 in dev::Worker::__lambda1::operator() (__closure=0x61bab0) at /home/minekraft/lefteris/cpp-ethereum/libdevcore/Worker.cpp:55
#24 0x00002aaaac609554 in std::_Bind_simple<dev::Worker::startWorking()::__lambda1()>::_M_invoke<>(std::_Index_tuple<>) (this=0x61bab0) at /usr/include/c++/4.8/functional:1732
#25 0x00002aaaac6094ab in std::_Bind_simple<dev::Worker::startWorking()::__lambda1()>::operator()(void) (this=0x61bab0) at /usr/include/c++/4.8/functional:1720
#26 0x00002aaaac609444 in std::thread::_Impl<std::_Bind_simple<dev::Worker::startWorking()::__lambda1()> >::_M_run(void) (this=0x61ba98) at /usr/include/c++/4.8/thread:115
#27 0x00002aaaacf9bbf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#28 0x00002aaaaccd4182 in start_thread (arg=0x2aaab88bf700) at pthread_create.c:312
#29 0x00002aaaad80447d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

It seems to be trying to remove something from TrieDB when the assertion hits.

**Comment by gavofyork** [comment]
fixed in latest.
