### ISSUE TITLE
Qt crash / infinite recursion

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#2211]
Backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4a8afd7 in ?? () from /opt/Qt/5.4/gcc_64/lib/libQt5Gui.so.5
(gdb) bt
#0  0x00007ffff4a8afd7 in ?? () from /opt/Qt/5.4/gcc_64/lib/libQt5Gui.so.5
#1  0x00007ffff4a8bca1 in ?? () from /opt/Qt/5.4/gcc_64/lib/libQt5Gui.so.5
#2  0x00007ffff4a916e6 in ?? () from /opt/Qt/5.4/gcc_64/lib/libQt5Gui.so.5
#3  0x00007ffff4a9858c in QTextLayout::beginLayout() () from /opt/Qt/5.4/gcc_64/lib/libQt5Gui.so.5
#4  0x00007ffff6fdb3d0 in ?? () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#5  0x00007ffff6fe6a97 in ?? () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#6  0x00007ffff6fe7518 in ?? () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#7  0x00007ffff6fe7ef5 in QCommonStyle::sizeFromContents(QStyle::ContentsType, QStyleOption const*, QSize const&, QWidget const*) const () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#8  0x00007ffff704c06e in ?? () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#9  0x00007ffff7266393 in QStyledItemDelegate::sizeHint(QStyleOptionViewItem const&, QModelIndex const&) const ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#10 0x00007ffff71f600e in ?? () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#11 0x00007ffff71f6480 in QListView::updateGeometries() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#12 0x00007ffff6faedf6 in QWidget::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#13 0x00007ffff70b5cf6 in QFrame::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#14 0x00007ffff71dc7bb in QAbstractItemView::viewportEvent(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#15 0x00007ffff797408d in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#16 0x00007ffff6f7327f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#17 0x00007ffff6f76c86 in QApplication::notify(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#18 0x00007ffff7973e24 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#19 0x00007ffff6faaad6 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#20 0x00007ffff6fab01f in QWidget::setGeometry(QRect const&) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#21 0x00007ffff713b53d in QAbstractScrollAreaPrivate::layoutChildren() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#22 0x00007ffff71f636d in QListView::updateGeometries() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#23 0x00007ffff6faedf6 in QWidget::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24 0x00007ffff70b5cf6 in QFrame::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#25 0x00007ffff71dc7bb in QAbstractItemView::viewportEvent(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#26 0x00007ffff797408d in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#27 0x00007ffff6f7327f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#28 0x00007ffff6f76c86 in QApplication::notify(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#29 0x00007ffff7973e24 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#30 0x00007ffff6faaad6 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#31 0x00007ffff6fab01f in QWidget::setGeometry(QRect const&) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#32 0x00007ffff713b53d in QAbstractScrollAreaPrivate::layoutChildren() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#33 0x00007ffff71f636d in QListView::updateGeometries() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#34 0x00007ffff6faedf6 in QWidget::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#35 0x00007ffff70b5cf6 in QFrame::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#36 0x00007ffff71dc7bb in QAbstractItemView::viewportEvent(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#37 0x00007ffff797408d in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#38 0x00007ffff6f7327f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#39 0x00007ffff6f76c86 in QApplication::notify(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#40 0x00007ffff7973e24 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#41 0x00007ffff6faaad6 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#42 0x00007ffff6fab01f in QWidget::setGeometry(QRect const&) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#43 0x00007ffff713b53d in QAbstractScrollAreaPrivate::layoutChildren() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#44 0x00007ffff71f636d in QListView::updateGeometries() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#45 0x00007ffff6faedf6 in QWidget::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#46 0x00007ffff70b5cf6 in QFrame::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#47 0x00007ffff71dc7bb in QAbstractItemView::viewportEvent(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#48 0x00007ffff797408d in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#49 0x00007ffff6f7327f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#50 0x00007ffff6f76c86 in QApplication::notify(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#51 0x00007ffff7973e24 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#52 0x00007ffff6faaad6 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#53 0x00007ffff6fab01f in QWidget::setGeometry(QRect const&) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#54 0x00007ffff713b53d in QAbstractScrollAreaPrivate::layoutChildren() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#55 0x00007ffff71f636d in QListView::updateGeometries() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#56 0x00007ffff6faedf6 in QWidget::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#57 0x00007ffff70b5cf6 in QFrame::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#58 0x00007ffff71dc7bb in QAbstractItemView::viewportEvent(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#59 0x00007ffff797408d in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#60 0x00007ffff6f7327f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#61 0x00007ffff6f76c86 in QApplication::notify(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#62 0x00007ffff7973e24 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#63 0x00007ffff6faaad6 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#64 0x00007ffff6fab01f in QWidget::setGeometry(QRect const&) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#65 0x00007ffff713b53d in QAbstractScrollAreaPrivate::layoutChildren() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#66 0x00007ffff71f636d in QListView::updateGeometries() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#67 0x00007ffff6faedf6 in QWidget::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#68 0x00007ffff70b5cf6 in QFrame::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#69 0x00007ffff71dc7bb in QAbstractItemView::viewportEvent(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#70 0x00007ffff797408d in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#71 0x00007ffff6f7327f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#72 0x00007ffff6f76c86 in QApplication::notify(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#73 0x00007ffff7973e24 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#74 0x00007ffff6faaad6 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#75 0x00007ffff6fab01f in QWidget::setGeometry(QRect const&) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#76 0x00007ffff713b53d in QAbstractScrollAreaPrivate::layoutChildren() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#77 0x00007ffff71f636d in QListView::updateGeometries() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#78 0x00007ffff6faedf6 in QWidget::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#79 0x00007ffff70b5cf6 in QFrame::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#80 0x00007ffff71dc7bb in QAbstractItemView::viewportEvent(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#81 0x00007ffff797408d in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#82 0x00007ffff6f7327f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#83 0x00007ffff6f76c86 in QApplication::notify(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#84 0x00007ffff7973e24 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#85 0x00007ffff6faaad6 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#86 0x00007ffff6fab01f in QWidget::setGeometry(QRect const&) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#87 0x00007ffff713b53d in QAbstractScrollAreaPrivate::layoutChildren() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#88 0x00007ffff71f636d in QListView::updateGeometries() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#89 0x00007ffff6faedf6 in QWidget::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#90 0x00007ffff70b5cf6 in QFrame::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#91 0x00007ffff71dc7bb in QAbstractItemView::viewportEvent(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#92 0x00007ffff797408d in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()  from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#93 0x00007ffff6f7327f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#94 0x00007ffff6f76c86 in QApplication::notify(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#95 0x00007ffff7973e24 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
...
#24769 0x00007ffff6faaad6 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24770 0x00007ffff6fab01f in QWidget::setGeometry(QRect const&) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24771 0x00007ffff713b53d in QAbstractScrollAreaPrivate::layoutChildren() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24772 0x00007ffff71f636d in QListView::updateGeometries() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24773 0x00007ffff6faedf6 in QWidget::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24774 0x00007ffff70b5cf6 in QFrame::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24775 0x00007ffff71dc7bb in QAbstractItemView::viewportEvent(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24776 0x00007ffff797408d in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24777 0x00007ffff6f7327f in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24778 0x00007ffff6f76c86 in QApplication::notify(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24779 0x00007ffff7973e24 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24780 0x00007ffff6faaad6 in QWidgetPrivate::setGeometry_sys(int, int, int, int, bool) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24781 0x00007ffff6fab01f in QWidget::setGeometry(QRect const&) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24782 0x00007ffff713b53d in QAbstractScrollAreaPrivate::layoutChildren() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24783 0x00007ffff713be41 in QAbstractScrollArea::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24784 0x00007ffff71dfbbb in QAbstractItemView::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24785 0x00007ffff6f732b4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24786 0x00007ffff6f76c86 in QApplication::notify(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24787 0x00007ffff7973e24 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24788 0x00007ffff6faa7c0 in QWidget::setContentsMargins(int, int, int, int) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24789 0x00007ffff713b78d in QAbstractScrollAreaPrivate::layoutChildren() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24790 0x00007ffff71f636d in QListView::updateGeometries() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24791 0x00007ffff71d5529 in QAbstractItemView::doItemsLayout() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24792 0x00007ffff71f3a9b in QListView::doItemsLayout() () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24793 0x00007ffff71fb8db in QListView::rectForIndex(QModelIndex const&) const () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24794 0x00007ffff71fb98e in QListView::visualRect(QModelIndex const&) const () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24795 0x00007ffff71fa948 in QListView::visualRegionForSelection(QItemSelection const&) const ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24796 0x00007ffff71d2329 in QAbstractItemView::selectionChanged(QItemSelection const&, QItemSelection const&) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24797 0x00007ffff71fb1ab in QListView::selectionChanged(QItemSelection const&, QItemSelection const&) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24798 0x00007ffff71de3d5 in ?? () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24799 0x00007ffff79a601a in QMetaObject::activate(QObject*, int, int, void**) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24800 0x00007ffff792a5b7 in QItemSelectionModel::selectionChanged(QItemSelection const&, QItemSelection const&) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24801 0x00007ffff792ff3f in QItemSelectionModel::emitSelectionChanged(QItemSelection const&, QItemSelection const&) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24802 0x00007ffff7931787 in QItemSelectionModel::select(QItemSelection const&, QFlags<QItemSelectionModel::SelectionFlag>) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24803 0x00007ffff792d89c in QItemSelectionModel::select(QModelIndex const&, QFlags<QItemSelectionModel::SelectionFlag>) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24804 0x00007ffff723af5f in QListWidget::setItemSelected(QListWidgetItem const*, bool) ()   from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24805 0x00000000006d7be1 in QListWidgetItem::setSelected (this=0x48f6bf0, aselect=true)    at /opt/Qt/5.4/gcc_64/include/QtWidgets/qlistwidget.h:307
#24806 0x00000000006c33fb in Main::<lambda(const h256&)>::operator()(const dev::h256 &) const (__closure=0x7fffffffc610, h=...)    at /home/chfast/Projects/ethereum/cpp-ethereum/alethzero/MainWin.cpp:1314
#24807 0x00000000006c50a6 in Main::refreshBlockChain (this=0x7fffffffd950)    at /home/chfast/Projects/ethereum/cpp-ethereum/alethzero/MainWin.cpp:1351
#24808 0x00000000006b3c1e in Main::onNewBlock (this=0x7fffffffd950)    at /home/chfast/Projects/ethereum/cpp-ethereum/alethzero/MainWin.cpp:470
#24809 0x00000000006b283b in Main::<lambda(const LocalisedLogEntries&)>::operator()(const dev::eth::LocalisedLogEntries &) const (    __closure=0x13e7290) at /home/chfast/Projects/ethereum/cpp-ethereum/alethzero/MainWin.cpp:382
#24810 0x00000000006d2da1 in std::_Function_handler<void(const std::vector<dev::eth::LocalisedLogEntry, std::allocator<dev::eth::LocalisedLogEntry> >&), Main::installWatches()::<lambda(const LocalisedLogEntries&)> >::_M_invoke(const std::_Any_data &, const std::vector<dev::eth::LocalisedLogEntry, std::allocator<dev::eth::LocalisedLogEntry> > &) (__functor=...,     __args#0=std::vector of length 51, capacity 64 = {...}) at /usr/include/c++/4.9/functional:2039
#24811 0x00000000006f7677 in std::function<void (std::vector<dev::eth::LocalisedLogEntry, std::allocator<dev::eth::LocalisedLogEntry> > const&)>::operator()(std::vector<dev::eth::LocalisedLogEntry, std::allocator<dev::eth::LocalisedLogEntry> > const&) const (    this=0x13eccf8, __args#0=std::vector of length 51, capacity 64 = {...}) at /usr/include/c++/4.9/functional:2439
#24812 0x00000000006c62da in Main::timerEvent (this=0x7fffffffd950)    at /home/chfast/Projects/ethereum/cpp-ethereum/alethzero/MainWin.cpp:1461
#24813 0x00007ffff79a8189 in QObject::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24814 0x00007ffff6fae9a2 in QWidget::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24815 0x00007ffff70cc80b in QMainWindow::event(QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24816 0x00007ffff6f732b4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24817 0x00007ffff6f76c86 in QApplication::notify(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#24818 0x00007ffff7973e24 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24819 0x00007ffff79cda54 in QTimerInfoList::activateTimers() () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24820 0x00007ffff79cdd31 in ?? () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24821 0x00007fffefefec3d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24822 0x00007fffefefef20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24823 0x00007fffefefefcc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24824 0x00007ffff79ce5e4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24825 0x00007ffff797204b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24826 0x00007ffff7976f65 in QCoreApplication::exec() () from /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24827 0x00000000006479e5 in main (argc=1, argv=0x7fffffffde48) at /home/chfast/Projects/ethereum/cpp-ethereum/alethzero/main.cpp:11
```

**Comment by gavofyork** [comment]
awesome. is this recent?

**Comment by gavofyork** [comment]
Moved to https://github.com/ethereum/alethzero/issues
