### ISSUE TITLE
Crash in boost::asio

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#2214]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff46a1ea8 in boost::asio::detail::op_queue_access::next<boost::asio::detail::task_io_service_operation> (o=0x886421eb9f885f)
    at /usr/include/boost/asio/detail/op_queue.hpp:35
35	    return static_cast<Operation*>(o->next_);
(gdb) bt
#0  0x00007ffff46a1ea8 in boost::asio::detail::op_queue_access::next<boost::asio::detail::task_io_service_operation> (
    o=0x886421eb9f885f) at /usr/include/boost/asio/detail/op_queue.hpp:35
#1  0x00007ffff469e8ab in boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>::pop (this=0x7fffffffd750)
    at /usr/include/boost/asio/detail/op_queue.hpp:97
#2  0x00007ffff469e4c6 in boost::asio::detail::op_queue<boost::asio::detail::task_io_service_operation>::~op_queue (
    this=0x7fffffffd750, __in_chrg=<optimized out>) at /usr/include/boost/asio/detail/op_queue.hpp:80
#3  0x00007ffff46c1e5b in boost::asio::detail::task_io_service::abandon_operations (this=0x1475660, ops=...)
    at /usr/include/boost/asio/detail/impl/task_io_service.ipp:334
#4  0x00007ffff46c101a in boost::asio::detail::epoll_reactor::shutdown_service (this=0x1475710)
    at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:89
#5  0x00007ffff4699b1b in boost::asio::detail::service_registry::~service_registry (this=0x1475610, __in_chrg=<optimized out>)
    at /usr/include/boost/asio/detail/impl/service_registry.ipp:37
#6  0x00007ffff469ba55 in boost::asio::io_service::~io_service (this=0x14909d0, __in_chrg=<optimized out>)
    at /usr/include/boost/asio/impl/io_service.ipp:53
#7  0x00007ffff46b3c8a in dev::p2p::Host::~Host (this=0x14908e0, __in_chrg=<optimized out>)
    at /home/chfast/Projects/ethereum/cpp-ethereum/libp2p/Host.cpp:115
#8  0x00007ffff7fd1d79 in dev::WebThreeDirect::~WebThreeDirect (this=0x14908d0, __in_chrg=<optimized out>)
    at /home/chfast/Projects/ethereum/cpp-ethereum/libwebthree/WebThree.cpp:60
#9  0x0000000000700092 in std::default_delete<dev::WebThreeDirect>::operator() (this=0x7fffffffd990, __ptr=0x14908d0)
    at /usr/include/c++/4.9/bits/unique_ptr.h:76
#10 0x00000000006f684b in std::unique_ptr<dev::WebThreeDirect, std::default_delete<dev::WebThreeDirect> >::~unique_ptr (
    this=0x7fffffffd990, __in_chrg=<optimized out>) at /usr/include/c++/4.9/bits/unique_ptr.h:236
#11 0x00000000006b18ea in Main::~Main (this=0x7fffffffd950, __in_chrg=<optimized out>)
    at /home/chfast/Projects/ethereum/cpp-ethereum/alethzero/MainWin.cpp:268
#12 0x00000000006479f6 in main (argc=1, argv=0x7fffffffde48) at /home/chfast/Projects/ethereum/cpp-ethereum/alethzero/main.cpp:8
```

**Comment by gavofyork** [comment]
presume fixed with alex's recent p2p changes. please reopen otherwise.
