### ISSUE TITLE
web3 in cpp is old 0.5.0, gulp error events.js:72 Unhandled 'error' event

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#2229]
develop a133519

web3.js repo is now at 0.6.0 but cpp-ethereum/libjsqrc/ethereumjs/package.json is still 0.5.0

also, with gulp 3.9.0, inside directory cpp-ethereum/libjsqrc/ethereumjs, running gulp is giving error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: SyntaxError: Unexpected end of input while parsing json file /home/user/cpp-ethereum/libjsqrc/ethereumjs/package.json
    at fns (/home/user/cpp-ethereum/libjsqrc/ethereumjs/node_modules/browserify/node_modules/module-deps/index.js:439:30)
    at fs.js:271:14
    at /home/user/cpp-ethereum/libjsqrc/ethereumjs/node_modules/bower/node_modules/bower-json/node_modules/graceful-fs/graceful-fs.js:104:5
    at /home/user/cpp-ethereum/libjsqrc/ethereumjs/node_modules/bower/node_modules/bower-registry-client/node_modules/graceful-fs/graceful-fs.js:104:5
    at /home/user/cpp-ethereum/libjsqrc/ethereumjs/node_modules/bower/node_modules/bower-config/node_modules/graceful-fs/graceful-fs.js:104:5
    at Object.oncomplete (fs.js:107:15)
```

**Comment by debris** [comment]
fixed in latest develop

**Comment by ethers** [comment]
thanks :)
