### ISSUE TITLE
Worker is null

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#2333]
It looks like the object that implements the Worker interface is null and when boost tries to execute virtual method doWork() the program crashes.

```
ASAN:SIGSEGV
=================================================================
==17394==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000090 (pc 0x7f572255ca0f bp 0x7f56fdf43750 sp 0x7f56fdf436e0 T45)
    #0 0x7f572255ca0e in boost::asio::detail::epoll_reactor::start_op(int, int, boost::asio::detail::epoll_reactor::descriptor_state*&, boost::asio::detail::reactor_op*, bool, bool) /usr/local/include/boost/asio/detail/impl/epoll_reactor.ipp:219:7
    #1 0x7f572255c8cd in boost::asio::detail::reactive_socket_service_base::start_op(boost::asio::detail::reactive_socket_service_base::base_implementation_type&, int, boost::asio::detail::reactor_op*, bool, bool, bool) /usr/local/include/boost/asio/detail/impl/reactive_socket_service_base.ipp:213:7
    #2 0x7f57225af9a4 in void boost::asio::detail::reactive_socket_service_base::async_receive<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::$_1::operator()(boost::system::error_code, unsigned long) const::{lambda(boost::system::error_code, unsigned long)#1}> >(boost::asio::detail::reactive_socket_service_base::base_implementation_type&, boost::asio::mutable_buffers_1 const&, int, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::$_1::operator()(boost::system::error_code, unsigned long) const::{lambda(boost::system::error_code, unsigned long)#1}>&) /usr/local/include/boost/asio/detail/reactive_socket_service_base.hpp:287:5
    #3 0x7f57225af8ce in boost::asio::async_result<boost::asio::handler_type<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::$_1::operator()(boost::system::error_code, unsigned long) const::{lambda(boost::system::error_code, unsigned long)#1}>, void (boost::system::error_code, unsigned long)>::type>::type boost::asio::stream_socket_service<boost::asio::ip::tcp>::async_receive<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::$_1::operator()(boost::system::error_code, unsigned long) const::{lambda(boost::system::error_code, unsigned long)#1}> >(boost::asio::detail::reactive_socket_service<boost::asio::ip::tcp>::implementation_type&, boost::asio::mutable_buffers_1 const&, int, boost::asio::handler_type&&) /usr/local/include/boost/asio/stream_socket_service.hpp:357:5
    #4 0x7f57225aecfc in boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::$_1::operator()(boost::system::error_code, unsigned long) const::{lambda(boost::system::error_code, unsigned long)#1}>::operator()(boost::system::error_code const&, unsigned long, int) /usr/local/include/boost/asio/impl/read.hpp:271:11
    #5 0x7f57225afb6f in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_all_t, dev::p2p::Session::doRead()::$_1::operator()(boost::system::error_code, unsigned long) const::{lambda(boost::system::error_code, unsigned long)#1}> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) /usr/local/include/boost/asio/detail/reactive_socket_recv_op.hpp:110:7
    #6 0x7f572253ce99 in boost::asio::detail::task_io_service::do_run_one(boost::asio::detail::scoped_lock<boost::asio::detail::posix_mutex>&, boost::asio::detail::task_io_service_thread_info&, boost::system::error_code const&) /usr/local/include/boost/asio/detail/impl/task_io_service.ipp:372:9
    #7 0x7f572253cca4 in boost::asio::detail::task_io_service::run(boost::system::error_code&) /usr/local/include/boost/asio/detail/impl/task_io_service.ipp:149:10
    #8 0x7f5722533b55 in boost::asio::io_service::run() /usr/local/include/boost/asio/impl/io_service.ipp:59:19
    #9 0x7f57205ae126 in dev::Worker::workLoop() /home/chfast/Projects/ethereum/cpp-ethereum/libdevcore/Worker.cpp:115:3
    #10 0x7f57205aea4f in dev::Worker::startWorking()::$_0::operator()() const /home/chfast/Projects/ethereum/cpp-ethereum/libdevcore/Worker.cpp:55:5
    #11 0x7f571f5a9e2f  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbae2f)
    #12 0x7f571f8056a9 in start_thread /build/buildd/glibc-2.21/nptl/pthread_create.c:333
    #13 0x7f571e901eec in clone /build/buildd/glibc-2.21/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /usr/local/include/boost/asio/detail/impl/epoll_reactor.ipp:219:7 in boost::asio::detail::epoll_reactor::start_op(int, int, boost::asio::detail::epoll_reactor::descriptor_state*&, boost::asio::detail::reactor_op*, bool, bool)
Thread T45 (p2p) created by T0 (alethzero) here:
    #0 0x5c81a9 in __interceptor_pthread_create /home/chfast/Projects/llvm/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:232
    #1 0x7f571f5a9f68 in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xbaf68)

==17394==ABORTING
```

**Comment by chfast** [comment]
Duplicate of #2101
