### ISSUE TITLE
Performance degradation in TransactionQueue

### ISSUE THREAD

**Issue by arkpar** [ethereum/cpp-ethereum#2356]
Once there are about 20000 transaction in the queue (of which 4000 are future) sync starts to miss blocks. Client spends to much time here:

```
#0  0x00000000004fe0a6 in boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>::compare<256u, 256u, (
boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void> (this=0x7fffe2295ad0, o=...) at /usr/include/boost/multiprecision/cpp_int.hpp:1675
1675          return compare_imp(o, t1(), t2());
(gdb) bt
#0  0x00000000004fe0a6 in boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>::compare<256u, 256u, (
boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void> (this=0x7fffe2295ad0, o=...) at /usr/include/boost/multiprecision/cpp_int.hpp:1675
#1  0x00000000004f1ad8 in boost::multiprecision::default_ops::eval_lt<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_in
t_check_type)0, void> > (a=..., b=...) at /usr/include/boost/multiprecision/detail/number_compare.hpp:44
#2  0x00000000004e350b in boost::multiprecision::operator< <boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_ty
pe)0, void>, (boost::multiprecision::expression_template_option)0> (a=..., b=...) at /usr/include/boost/multiprecision/detail/number_compare.hpp:196
#3  0x00007ffff74e351b in std::max<boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_che
ck_type)0, void>, (boost::multiprecision::expression_template_option)0> > (__a=..., __b=...) at /usr/include/c++/4.8/bits/stl_algobase.h:221
#4  0x00007ffff751e418 in dev::eth::TransactionQueue::maxNonce_WITH_LOCK (this=0x5d56d0, _a=...) at /home/arkady/src/cpp-ethereum/libethereum/TransactionQueue.cpp:173
#5  0x00007ffff751da95 in dev::eth::TransactionQueue::transactions (this=0x5d56d0) at /home/arkady/src/cpp-ethereum/libethereum/TransactionQueue.cpp:103
#6  0x00007ffff75268df in dev::eth::EthereumHost::maintainTransactions (this=0xbda690) at /home/arkady/src/cpp-ethereum/libethereum/EthereumHost.cpp:118
#7  0x00007ffff7526365 in dev::eth::EthereumHost::doWork (this=0xbda690) at /home/arkady/src/cpp-ethereum/libethereum/EthereumHost.cpp:98
```
Looks like an O(N*M) algorithm, should be replaced with something more efficient.

**Comment by arkpar** [comment]
Implemented a prioritized queue
