### ISSUE TITLE
Return type uint[] dynamic and fixed size causing problems.

### ISSUE THREAD

**Issue by Georgi87** [ethereum/cpp-ethereum#2519]
Testing with pyethereum I got some errors returning uint arrays of fixed and dynamic size.

t1 works but t2 returning an fixed size array breaks and also t3 returning an dynamic size array with one assigend value breaks. The error message is below each function.

```
contract TestContract {

    function t1() returns (uint[]) {
        uint[] t_array;
        return t_array;
    }
    /* this one works */

    function t2() returns (uint[16]) {
        uint[16] t_array;
        return t_array;
    }

    /*
    Traceback (most recent call last):
      File "bug_test.py", line 22, in test_1
        print self.c.t2()
      File "/home/vagrant/pyethereum/ethereum/tester.py", line 98, in kall
        outdata = self._translator.decode(f, o['output'])
      File "/home/vagrant/pyethereum/ethereum/abi.py", line 76, in decode
        o = decode_abi(fdata['decode_types'], data)
      File "/home/vagrant/pyethereum/ethereum/abi.py", line 398, in decode_abi
        return [dec(proctypes[i], outs[i]) for i in range(len(outs))]
      File "/home/vagrant/pyethereum/ethereum/abi.py", line 437, in dec
        for i in range(L)]
    TypeError: range() integer end argument expected, got list.
    */

    function t3() returns (uint[]) {
        uint[] t_array;
        t_array[0] = 1;
        return t_array;
    }
    /*
    Traceback (most recent call last):
      File "bug_test.py", line 21, in test_1
        print self.c.t3()
      File "/home/vagrant/pyethereum/ethereum/tester.py", line 91, in kall
        **dict_without(kwargs, 'sender', 'value', 'output'))
      File "/home/vagrant/pyethereum/ethereum/tester.py", line 192, in _send
        raise Exception("Transaction failed")
    Exception: Transaction failed
    */
}
```

**Comment by chriseth** [comment]
Unfortunately, this is a pitfall the compiler does not yet warn you about. I just added a [section](https://github.com/ethereum/wiki/wiki/Solidity-Tutorial#pitfalls) to the tutorial. Fixed-size arrays work if you add the keyword `memory` to the type. Dynamic arrays do not (yet) function in memory, i.e. you cannot change their size.

**Comment by Georgi87** [comment]
Good to know. Thanks for the info chris.
