### ISSUE TITLE
ArchLinux and our v8 dependency, setVerbosity() segfault

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/cpp-ethereum#2598]
This is not a priority for the release but I have to document that I am having trouble with the v8 dependency that the new JS console has introduced.

In ArchLinux the latest v8 package is `v8-svn` (?)  and is not API compatible with our project. From the ones that are API compatible I tried both [3.14](https://aur.archlinux.org/packages/v8-3.14/) and [3.15](https://aur.archlinux.org/packages/v8-3.15/).

Our project compiles fine, the JS console is kind of usable but when I try to set the verbosity I get a segfault which appears to be in both cases inside the library.

```
> web3.admin.web3.setVerbosity(5)
[New Thread 0x7fffec052700 (LWP 8014)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff393c760 in _int_malloc () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff393c760 in _int_malloc () from /usr/lib/libc.so.6
#1  0x00007ffff393e8be in malloc () from /usr/lib/libc.so.6
#2  0x00007ffff4bbc61a in Json::Value::CZString::CZString(Json::Value::CZString const&) () from /usr/lib/libjsoncpp.so.1
#3  0x00007ffff4bc3b49 in Json::Value::resolveReference(char const*, char const*) () from /usr/lib/libjsoncpp.so.1
#4  0x00007ffff5938f19 in jsonrpc::RpcProtocolServerV2::WrapError(Json::Value const&, int, std::string const&, Json::Value&) () from /usr/lib/libjsonrpccpp-server.so.0
#5  0x00007ffff5939415 in jsonrpc::RpcProtocolServerV2::WrapException(Json::Value const&, jsonrpc::JsonRpcException const&, Json::Value&) () from /usr/lib/libjsonrpccpp-server.so.0
#6  0x00007ffff59395d0 in jsonrpc::RpcProtocolServerV2::HandleSingleRequest(Json::Value const&, Json::Value&) () from /usr/lib/libjsonrpccpp-server.so.0
#7  0x00007ffff593989e in jsonrpc::RpcProtocolServerV2::HandleJsonRequest(Json::Value const&, Json::Value&) () from /usr/lib/libjsonrpccpp-server.so.0
#8  0x00007ffff593b4d5 in jsonrpc::AbstractProtocolHandler::HandleRequest(std::string const&, std::string&) () from /usr/lib/libjsonrpccpp-server.so.0
#9  0x00007ffff593af27 in jsonrpc::AbstractServerConnector::OnRequest(std::string const&, void*) () from /usr/lib/libjsonrpccpp-server.so.0
#10 0x00007ffff7ee2f15 in dev::eth::JSV8Connector::onSend (this=0x1096890, payload=<optimized out>) at /home/lefteris/ew/cpp-ethereum/libjsconsole/JSV8Connector.cpp:48
#11 0x00007ffff58eb79c in dev::eth::JSV8RPCSend (_args=...) at /home/lefteris/ew/cpp-ethereum/libjsengine/JSV8RPC.cpp:48
#12 0x00007ffff5319236 in ?? () from /usr/lib/libv8.so
#13 0x000034ebbba0618e in ?? ()
#14 0x000034ebbba060e1 in ?? ()
#15 0x00007fffffffb700 in ?? ()
#16 0x00007fffffffb758 in ?? ()
#17 0x000034ebbba7609f in ?? ()
#18 0x00003ebcb080e081 in ?? ()
#19 0x0000263841f4b379 in ?? ()
#20 0x0000263841f49269 in ?? ()
#21 0x000007b06b204121 in ?? ()
#22 0x0000263841f4b379 in ?? ()
#23 0x000007b06b264819 in ?? ()
#24 0x0000263841f0f2e9 in ?? ()
#25 0x00007fffffffb798 in ?? ()
#26 0x000034ebbba601e1 in ?? ()
#27 0x0000263841f4ade1 in ?? ()
#28 0x0000263841f4a151 in ?? ()
#29 0x0000263841f37c29 in ?? ()
#30 0x0000263841f4aa79 in ?? ()
#31 0x000007b06b2675a1 in ?? ()
#32 0x0000263841f4aa39 in ?? ()
#33 0x00007fffffffb7c8 in ?? ()
#34 0x000034ebbba0a96e in ?? ()
#35 0x0000263841f37c29 in ?? ()
#36 0x0000000100000000 in ?? ()
#37 0x000007b06b2675a1 in ?? ()
#38 0x0000000800000000 in ?? ()
#39 0x00007fffffffb808 in ?? ()
#40 0x000034ebbba245e1 in ?? ()
#41 0x0000000500000000 in ?? ()
#42 0x0000263841f37c29 in ?? ()
#43 0x000007b06b2675a1 in ?? ()
#44 0x000034ebbba24521 in ?? ()
#45 0x0000000600000000 in ?? ()
#46 0x0000000000000000 in ?? ()
(gdb) frame 10
#10 0x00007ffff7ee2f15 in dev::eth::JSV8Connector::onSend (this=0x1096890, payload=<optimized out>) at /home/lefteris/ew/cpp-ethereum/libjsconsole/JSV8Connector.cpp:48
48              OnRequest(payload, NULL);
(gdb) p payload
$1 = <optimized out>
(gdb) 
```

Will not focus on this now, but we should try to get this sorted at some point. I can try when I have more time.

**Comment by LefterisJP** [comment]
This segfault no longer happens. I am not really sure why, but will close for now. Could actually not be ArchLinux related but had to do something with my system at the time.
