### ISSUE TITLE
Segfault with malformed account hex in sendTransaction

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/cpp-ethereum#2793]
I got a segfault when trying to send a transaction with a not fully written out hexadecimal. I wrote the code below in order to send a transaction.

```
web3.eth.sendTransaction({from: web3.eth.coinbase, to: '0x0', value: "0x2"})
```

and got the following trace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff2f367a0 in Json::Value::CommentInfo::~CommentInfo() () from /usr/lib/libjsoncpp.so.1
(gdb) bt
#0  0x00007ffff2f367a0 in Json::Value::CommentInfo::~CommentInfo() () from /usr/lib/libjsoncpp.so.1
#1  0x00007ffff2f3bbef in Json::Value::~Value() () from /usr/lib/libjsoncpp.so.1
#2  0x00007ffff7672658 in jsonrpc::JsonRpcException::~JsonRpcException() () from /usr/lib/libjsonrpccpp-common.so.0
#3  0x00007ffff7f144f1 in boost::exception_detail::error_info_injector<jsonrpc::JsonRpcException>::~error_info_injector (this=0x7fffffff9e60) at /usr/include/boost/exception/exception.hpp:338
#4  0x00007ffff7f143e3 in boost::throw_exception<boost::exception_detail::error_info_injector<jsonrpc::JsonRpcException> > (e=...) at /usr/include/boost/throw_exception.hpp:73
#5  0x00007ffff7ef9d85 in boost::exception_detail::throw_exception_<jsonrpc::JsonRpcException> (x=..., 
    current_function=0x7ffff7f7ac78 <.L__PRETTY_FUNCTION__._ZN3dev22WebThreeStubServerBase19eth_sendTransactionERKN4Json5ValueE> "virtual string dev::WebThreeStubServerBase::eth_sendTransaction(const Json::Value &)", 
    file=0x7ffff7f7a97e <.L.str43> "/home/lefteris/ew/cpp-ethereum/libweb3jsonrpc/WebThreeStubServerBase.cpp", line=259) at /usr/include/boost/throw_exception.hpp:86
#6  0x00007ffff7ee9547 in dev::WebThreeStubServerBase::eth_sendTransaction (this=0x18a9450, _json=...) at /home/lefteris/ew/cpp-ethereum/libweb3jsonrpc/WebThreeStubServerBase.cpp:259
#7  0x00007ffff7efea99 in AbstractWebThreeStubServer::eth_sendTransactionI (this=0x18a9450, request=..., response=...) at /home/lefteris/ew/cpp-ethereum/libweb3jsonrpc/abstractwebthreestubserver.h:200
#8  0x00007ffff7efd7a9 in jsonrpc::AbstractServer<AbstractWebThreeStubServer>::HandleMethodCall (this=0x18a9450, proc=..., input=..., output=...) at /usr/local/include/jsonrpccpp/server/abstractserver.h:57
#9  0x00007ffff41be791 in jsonrpc::AbstractProtocolHandler::ProcessRequest(Json::Value const&, Json::Value&) () from /usr/lib/libjsonrpccpp-server.so.0
#10 0x00007ffff41bba0c in jsonrpc::RpcProtocolServerV2::HandleSingleRequest(Json::Value const&, Json::Value&) () from /usr/lib/libjsonrpccpp-server.so.0
#11 0x00007ffff41bb912 in jsonrpc::RpcProtocolServerV2::HandleJsonRequest(Json::Value const&, Json::Value&) () from /usr/lib/libjsonrpccpp-server.so.0
#12 0x00007ffff41be4ba in jsonrpc::AbstractProtocolHandler::HandleRequest(std::string const&, std::string&) () from /usr/lib/libjsonrpccpp-server.so.0
#13 0x00007ffff41be267 in jsonrpc::AbstractServerConnector::OnRequest(std::string const&, void*) () from /usr/lib/libjsonrpccpp-server.so.0
#14 0x00007ffff70fbac3 in dev::eth::JSV8Connector::onSend (this=0x18a9410, payload=0x18e37b0 "{\"jsonrpc\":\"2.0\",\"method\":\"eth_sendTransaction\",\"params\":[{\"from\":\"0xa62645a1d62be11e4f3e0974847ed273ded7616a\",\"to\":\"0x0\",\"value\":\"0x2\"}],\"id\":14}")
    at /home/lefteris/ew/cpp-ethereum/libjsconsole/JSV8Connector.cpp:48
#15 0x00007ffff70fbb4f in non-virtual thunk to dev::eth::JSV8Connector::onSend(char const*) () at /home/lefteris/ew/cpp-ethereum/libjsconsole/JSV8Connector.cpp:46
#16 0x00007ffff4151f28 in dev::eth::JSV8RPCSend (_args=...) at /home/lefteris/ew/cpp-ethereum/libjsengine/JSV8RPC.cpp:50
#17 0x00000168da69913b in ?? ()
#18 0x00007fffffffab40 in ?? ()
#19 0x00007fffffffab48 in ?? ()
#20 0x0000000000000001 in ?? ()
#21 0x0000000000000000 in ?? ()
```

**Comment by gavofyork** [comment]
json rpc exception looks suspicious. @debris?
