### ISSUE TITLE
Alethzero segfault when deleting web3 directory

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/cpp-ethereum#2821]
When I deleted the `.web3` directory along with my account, Alethzero segfaulted in this part of the code. Fix should be easy.

Log gives out a message for missing key
```
Using host libthread_db library "/usr/lib/libthread_db.so.1".32
  ✘  02:18:28 AM|alethzero  Missing key: #b575607c… @a62645a1…
State root: d7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544
```

and the segfault follows soon after

```
Program received signal SIGSEGV, Segmentation fault.
dev::az::Main::setBeneficiary (this=0x7fffffffdab8, _b=...) at /home/lefteris/ew/cpp-ethereum/alethzero/MainWin.cpp:1152
1152            m_beneficiary = _b;
(gdb) bt
#0  dev::az::Main::setBeneficiary (this=0x7fffffffdab8, _b=...) at /home/lefteris/ew/cpp-ethereum/alethzero/MainWin.cpp:1152
#1  0x00000000004d38e2 in dev::az::Main::Main (this=0x7fffffffdab8, _parent=<optimized out>) at /home/lefteris/ew/cpp-ethereum/alethzero/MainWin.cpp:225
#2  0x00000000005267a0 in main (argc=<optimized out>, argv=<optimized out>) at /home/lefteris/ew/cpp-ethereum/alethzero/main.cpp:8
```

**Comment by LianaHus** [comment]
hmm I can't reproduce that.
develop on 51a7d57a1811523fc367eeded40626b38c7e43d4

**Comment by LefterisJP** [comment]
I tried with  51a7d57a1811523fc367eeded40626b38c7e43d4

Here is the output of the whole process.

1) Open Alethzero, all works okay.
```
 .SAFE  lefteris  ~  ew  cpp-ethereum  build  ./alethzero/alethzero                                                                                                                                                                                          develop 
./alethzero/alethzero: /opt/cuda/lib64/libOpenCL.so.1: no version information available (required by /home/lefteris/ew/cpp-ethereum/build/libethash-cl/libethash-cl.so)
  ℹ  11:03:59 AM|alethzero  Reading /home/lefteris/.web3/keys/9ab10d06-8ea0-8a30-fc8b-9f99976303cc.json
State root: d7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544
Block Hash: d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
Block RLP: [ [ "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x1DCC4DE8DEC75D7AAB85B567B6CCD41AD312451B948A7413F0A142FD40D49347, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00", 0xD7F8974FB5AC78D9AC099B9AD5018BEDC2CE0A72DAD1827A1709DA30580F0544, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, "\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x400000000, 0x0, 0x1388, 0x0, 0x0, 0x11BBE8DB4E347B4E8C937C1C8370E4B5ED33ADB3DB69CBDB7A38E1E50B1B82FA, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", "\x00\x00\x00\x00\x00\x00\x00B" ], [ ], [ ] ]
Block Hex: f90219f90214a00000000000000000000000000000000000000000000000000000000000000000a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347940000000000000000000000000000000000000000a0d7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000850400000000808213888080a011bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82faa00000000000000000000000000000000000000000000000000000000000000000880000000000000042c0c0
eth Network protocol version: 61
Client database version: 12041
⧎ ℹ  11:04:21 AM|alethzero  Id: ##4fb627d5…
  ℹ  11:04:22 AM|alethzero  Opened blockchain DB. Latest: #d4e56740… (rebuild not needed)
  ℹ  11:04:22 AM|alethzero  Opened state DB.
 ⚡   11:04:24 AM|alethzero  Stop worker 856 ms
  ℹ  11:04:24 AM|alethzero  Closing blockchain DB
  ℹ  11:04:24 AM|alethzero  Opened blockchain DB. Latest: #f840bcf4… (rebuild not needed)
  ℹ  11:04:24 AM|alethzero  Opened state DB.
 ⚡   11:04:26 AM|eth  Worker stopping 1789 ms
  ◇  11:04:26 AM|alethzero  newBlock watch ID: 0
  ◇  11:04:26 AM|alethzero  newPending watch ID: 1
  ◇  11:04:26 AM|alethzero  newBlock watch ID: 2
  ◇  11:04:26 AM|alethzero  newPending watch ID: 3
 ⚡   11:04:27 AM|alethzero  void dev::az::AllAccounts::refresh() 935 ms
 ⚡   11:04:27 AM|alethzero  void dev::az::Main::refreshBlockChain() 624 ms
"Error downloading DApp: " Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: dev::Exception
std::exception::what: std::exception
[dev::tag_comment*] = Dapp content hash does not match

"Error downloading DApp: " Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: dev::Exception
std::exception::what: std::exception
[dev::tag_comment*] = Dapp content hash does not match

 ⚡   11:04:34 AM|alethzero  Stop worker 314 ms
  ℹ  11:04:34 AM|alethzero  Closing blockchain DB
  ℹ  11:04:34 AM|alethzero  Closing state DB
```


2) Delete The keys and restart Alethzero
```
 .SAFE  lefteris  ~  ew  cpp-ethereum  build  rm -rf ~/.web3/                                                                                                                                                                                                develop 
 .SAFE  lefteris  ~  ew  cpp-ethereum  build  ./alethzero/alethzero                                                                                                                                                                                          develop 
./alethzero/alethzero: /opt/cuda/lib64/libOpenCL.so.1: no version information available (required by /home/lefteris/ew/cpp-ethereum/build/libethash-cl/libethash-cl.so)
  ✘  11:04:48 AM|alethzero  Missing key: #9ab10d06… @00d0df94…
State root: d7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544
Block Hash: d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3
Block RLP: [ [ "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x1DCC4DE8DEC75D7AAB85B567B6CCD41AD312451B948A7413F0A142FD40D49347, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00", 0xD7F8974FB5AC78D9AC099B9AD5018BEDC2CE0A72DAD1827A1709DA30580F0544, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, "\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x400000000, 0x0, 0x1388, 0x0, 0x0, 0x11BBE8DB4E347B4E8C937C1C8370E4B5ED33ADB3DB69CBDB7A3
8E1E50B1B82FA, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", "\x00\x00\x00\x00\x00\x00\x00B" ], [ ], [ ] ]
Block Hex: f90219f90214a00000000000000000000000000000000000000000000000000000000000000000a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347940000000000000000000000000000000000000000a0d7f8974fb5ac78d9ac099b9ad5018bedc2ce0a72dad1827a1709da30580f0544a056e81
f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000850400000000808213888080a011bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82faa0000000000000000000000000000000000000000000000000000000000000000088000000000
0000042c0c0
eth Network protocol version: 61
Client database version: 12041
⧎ ℹ  11:04:50 AM|alethzero  Id: ##4fb627d5…
  ℹ  11:04:51 AM|alethzero  Opened blockchain DB. Latest: #d4e56740… (rebuild not needed)
  ℹ  11:04:51 AM|alethzero  Opened state DB.
[1]    1288 segmentation fault (core dumped)  ./alethzero/alethzero
```
