### ISSUE TITLE
Synchronous requests are not supported by the IPC provider.

### ISSUE THREAD

**Issue by GiveMeSunShine** [ethereum/cpp-ethereum#3027]
I used Ethereum C++ client on my machiney  , when i use eth console to executive command as web3.eth.blockNumber, The console message is:
   **Error: You tried to send "eth_blockNumber" synchronously. Synchronous requests are not supported by the IPC provider.
    at IpcProvider.send (/usr/lib/node_modules/ethereum-console/node_modules/web3/lib/web3/ipcprovider.js:192:15)
    at RequestManager.send (/usr/lib/node_modules/ethereum-console/node_modules/web3/lib/web3/requestmanager.js:58:32)
    at Eth.get [as blockNumber](/usr/lib/node_modules/ethereum-console/node_modules/web3/lib/web3/property.js:107:62)
    at repl:1:9
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at REPLServer.defaultEval (repl.js:308:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval](domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:489:10)
    at emitOne (events.js:96:13)**

Almost all command will appear such mistakes , I don't know why,Anyone ever had this problem or Can someone help me to answer this question?

**Comment by chriseth** [comment]
All web3 function require (or at least accept) a callback function as their last argument. Some web3 consoles handle that for you, but the cpp-ethereum console requires you to specify the callback manually. You can just use `console.log` as the callback.
