### ISSUE TITLE
Error: Failed to subscribe to new newBlockHeaders to confirm the transaction receipts.

### ISSUE THREAD

**Issue by wangmaodong** [ethereum/cpp-ethereum#4898]
`> web3.eth.sendTransaction({from: "0xF97190f834B08fd0B2f38a949c975f05CA55DA6B", to:"0x0Ff2ea411Fd215e2D802a7729534A942c2f28DE4",value:web3.utils.toWei('1',"ether")})
Error: Failed to subscribe to new newBlockHeaders to confirm the transaction receipts.
{}
    at Object._fireError (/usr/local/lib/node_modules/ethereum-console/node_modules/web3-utils/src/index.js:56:17)
    at checkConfirmation (/usr/local/lib/node_modules/ethereum-console/node_modules/web3-core-method/src/index.js:399:19)
    at /usr/local/lib/node_modules/ethereum-console/node_modules/web3-core-subscriptions/src/subscription.js:303:19
    at Object.<anonymous> (/usr/local/lib/node_modules/ethereum-console/node_modules/web3-core-requestmanager/src/index.js:140:20)
    at IpcProvider.callback (/usr/local/lib/node_modules/ethereum-console/node_modules/web3-providers-ipc/src/index.js:65:40)
    at Array.forEach (native)
    at Object.Call (/usr/local/lib/node_modules/ethereum-console/node_modules/es6-shim/es6-shim.js:307:14)
    at Array.forEach (/usr/local/lib/node_modules/ethereum-console/node_modules/es6-shim/es6-shim.js:1313:17)
    at Socket.<anonymous> (/usr/local/lib/node_modules/ethereum-console/node_modules/web3-providers-ipc/src/index.js:76:51)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
`

**Comment by melhindi** [comment]
I also got this error message when trying to deploy a new contract with aleth.
Running the node with -v 4 gave more insights:
```
2018-09-10 13:44:17  rpc {"jsonrpc":"2.0","id":34,"method":"eth_subscribe","params":["newHeads"]}
2018-09-10 13:44:17  rpc {"error":{"code":-32601,"message":"METHOD_NOT_FOUND: The method being requested is not available on this server"},"id":34,"jsonrpc":"2.0"}
```
It looks like eth_subscribe is not implemented yet

**Comment by fdouglis** [comment]
Bump ... I know this isn't really being developed anymore, but was this issue really never addressed? Is there a workaround?
