### ISSUE TITLE
Descriptive error messages should be returned when web3.eth.sendTransaction fails due to account / user issues 

### ISSUE THREAD

**Issue by halfalicious** [ethereum/cpp-ethereum#5090]
Once #5076 is merged, descriptive error messages will be returned when `web3.eth.sendTransaction` fails, with the exception of account / user-related errors (e.g. account is locked, user-rejected tx). If sending a transaction fails because of an account or user-related error, a generic RPC "invalid method parameters" message is returned. For example, take the following case of a user-rejected tx:

	
```C:\Users\nilse\Documents\temp>geth attach ipc:\\.\pipe\geth.ipc
	Welcome to the Geth JavaScript console!
	
	instance: aleth/1.4.0.dev1+commit.05a43ac3.dirty/windows/msvc19.14.26430.0/relwithdebinfo
	coinbase: 0x0000000000000000000000000000000000000000
	> web3.eth.sendTransaction({from: personal.listAccounts[0], to: personal.listAccounts[1], value:web3.toWei(0)})
	Error: INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised
	    at web3.js:3143:20
	    at web3.js:6347:15
	    at web3.js:5081:36
	    at <anonymous>:1:1
```

Note that the expected exception error messages in the `sendingShouldFail `tests in `ClientTests/Personal `will also need to be updated. These tests can be found here: https://github.com/ethereum/cpp-ethereum/blob/dacd74b4d0bba7ef131b19726e4346662f3dd4de/test/unittests/libweb3jsonrpc/Client.cpp#L109-L132

**Comment by halfalicious** [comment]
@gumb0: This can be closed too, it's been addressed by #5117.
